services:

  socks5client:
    container_name: "nym_socks5client_${mixcorr_exp_run}"
    image: "mixmatch/nym-socks5-client:nym-binaries-1.0.2"
    pull_policy: "never"
    restart: "no"
    entrypoint: "bash -c 'printf \"nym_socks5client_${mixcorr_exp_run} is running, will sleep forever now...\n\" && sleep infinity'"
    env_file: "./nym_env_variables.env"
    environment:
      - "mixcorr_exp_id=${mixcorr_exp_id}"
      - "mixcorr_exp_run=${mixcorr_exp_run}"
    volumes:
      - "${mixcorr_res_dir}:/root/data"
